ecommerce/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from main.urls import urlpatterns as main_urls
from dashboard.urls import urlpatterns as dashboard_urls


MEDIA_DIR = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
STATIC_DIR = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
admin.site.site_header = '{} Admin Panel'.format(settings.SITE_TITLE)


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include(main_urls)),
    url(r'', include(dashboard_urls)),
] + MEDIA_DIR + STATIC_DIR

main/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from main.views import *


urlpatterns = [
    url(r'^$', home_view, name='home'),

    url(r'^accounts/register/$', register_view, name='register'),
    url(r'^accounts/login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^accounts/profile/$', profile_view, name='profile'),
    url(r'^accounts/profile/update-password/$', update_password_view, name='update_password'),
    url(r'^accounts/profile/update-photo$', update_photo_view, name='update_photo'),
    url(r'^accounts/profile/delete-photo$', delete_photo_view, name='delete_photo'),

    url(r'^category/(?P<category_id>\d+)?/?$', product_list_view, name='product_list'),
    url(r'^search/$', product_list_view, name='search'),
    url(r'^product/(?P<product_id>\d+)/$', product_details_view, name='product_details'),
    url(r'^product/(?P<product_id>\d+)/add_review/$', add_review_view, name='product_add_review'),
    url(r'^product/(?P<product_id>\d+)/add_to_cart/$', add_to_cart_view, name='product_add_to_cart'),
    url(r'^remove-review/(?P<review_id>\d+)/$', remove_review_view, name='remove_review'),

    url(r'^cart/checkout/$', cart_checkout_view, name='cart_checkout'),
    url(r'^cart/remove-item/(?P<item_id>\d+)/$', remove_cartitem_view, name='remove_cartitem'),
    url(r'^cart/clear/$', cart_clear_view, name='cart_clear'),

    url(r'^warranty-claim/$', warranty_claim_view, name='warranty_claim'),
]

main/models.py
import os
from django.conf import settings
from django.db import models
from django.db.models import Avg
from django.contrib.auth.admin import User
from django.utils.timezone import now, timedelta


class Customer(models.Model):
    user = models.OneToOneField(User, related_name='customer')
    photo = models.ImageField('Photo', null=True, blank=True, upload_to=settings.USER_PHOTOS_DIR)
    home_address = models.TextField('Home address', null=True, blank=True)
    phone_number = models.CharField('Phone number', max_length=15, null=True, blank=True)

    def __str__(self):
        return 'Customer < User: {}'.format(self.user.username)

    def get_photo_url(self):
        if not self.photo:
            return settings.BLANK_PROFILE_PHOTO_URL
        return str(self.photo).replace(settings.MEDIA_ROOT, settings.MEDIA_URL)


class Office(models.Model):
    name = models.CharField('Name', max_length=50)
    office_type = models.CharField('Office type', max_length=10, choices=(('branch', 'Branch office'),
                                                                          ('head', 'Head office'),))
    manager = models.ForeignKey(User, related_name='manager')
    postal_address = models.TextField('Office address', null=True, blank=True)
    phone_number = models.CharField('Phone number', max_length=15, null=True, blank=True)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField('Name', max_length=25)

    def __str__(self):
        return 'Category: {}'.format(self.name)

    class Meta:
        verbose_name_plural = 'Categories'


class InstallmentScheme(models.Model):
    name = models.CharField('Name', max_length=15)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Name', max_length=100)
    description = models.TextField('Description', blank=True, null=True)
    short_description = models.TextField('Short description', blank=True, null=True)
    default_price = models.FloatField('Default price', default=0.0)
    photo = models.ImageField('Photo', null=True, blank=True, upload_to=settings.PHOTO_DIR)
    photo_caption = models.CharField('Photo caption', max_length=30, null=True, blank=True)
    warranty_period = models.IntegerField('Warranty period (month)', default=0)
    offered_schemes = models.ManyToManyField(InstallmentScheme, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True)
    rating = models.FloatField('Product rating', blank=True, null=True)
    is_featured = models.BooleanField('Featured', default=False, help_text='Show this product in front page')

    def __str__(self):
        return 'Product: {}'.format(self.name)

    @property
    def stock_quantity(self):
        quantity = 0
        for stock in self.stock_set.all():
            quantity += stock.quantity
        return quantity

    @property
    def avg_rating(self):
        if self.rating is not None:
            return self.rating
        return Review.objects.filter(product=self).aggregate(Avg('rating')).get('rating__avg') or 0.0

    def get_photo_url(self):
        if not self.photo:
            return settings.BLANK_ITEM_PHOTO_URL
        return settings.MEDIA_URL + str(self.photo).replace(settings.MEDIA_ROOT, '')

    def as_dict(self):
        return {'id': self.id, 'name': self.name}


class ProductVariation(models.Model):
    name = models.CharField('Name', max_length=50)
    custom_price = models.FloatField('Custom price', default=0.0)
    product = models.ForeignKey(Product)

    def __str__(self):
        return 'Variation: {}'.format(self.name)


class ProductAttachment(models.Model):
    name = models.CharField('Name', max_length=50)
    extra_price = models.FloatField('Extra price', default=0.0)
    product = models.ForeignKey(Product)

    def __str__(self):
        return 'Attachment: {}'.format(self.name)


class Stock(models.Model):
    office = models.ForeignKey(Office)
    product = models.ForeignKey(Product)
    quantity = models.IntegerField('Quantity', default=0)

    def __str__(self):
        return 'Stock @ {} ({})'.format(self.office.name, self.quantity)


class Cart(models.Model):
    customer = models.ForeignKey(Customer)
    checkout_at = models.DateTimeField('Sold at', blank=True, null=True)
    delivery_address = models.TextField('Delivery address', null=True, blank=True)
    contact_phone = models.CharField('Contact phone', max_length=15, null=True, blank=True)
    completed_at = models.DateTimeField('Completed at', blank=True, null=True)
    amount_charged = models.FloatField('Amount charged', blank=True, null=True)

    def __str__(self):
        return 'Cart #{}'.format(self.id)

    @property
    def total(self):
        if self.amount_charged is not None:
            return self.amount_charged
        return sum([x.subtotal for x in self.cartitem_set.all()])


class CartItem(models.Model):
    product = models.ForeignKey(Product)
    product_variation = models.ForeignKey(ProductVariation, blank=True, null=True)
    product_attachment = models.ManyToManyField(ProductAttachment, blank=True)
    quantity = models.IntegerField('Quantity', default=1)
    chosen_scheme = models.ForeignKey(InstallmentScheme, blank=True, null=True)
    cart = models.ForeignKey(Cart)

    def __str__(self):
        return 'Sale item #{}'.format(self.id)

    @property
    def subtotal(self):
        base_price = self.product.default_price if self.product_variation is None else self.product_variation.custom_price
        if base_price == 0.0: base_price = self.product.default_price
        extra_price = 0.0
        for att in self.product_attachment.all():
            extra_price += att.extra_price
        return (base_price + extra_price) * self.quantity

    @property
    def warranty_available(self):
        warranty_period = timedelta(days=(self.product.warranty_period * 30))
        time_since_purchase = now() - self.cart.completed_at
        return warranty_period > time_since_purchase


class Review(models.Model):
    customer = models.ForeignKey(Customer)
    product = models.ForeignKey(Product)
    rating = models.IntegerField('Rating number', default=0)
    message = models.TextField('Message', blank=True, null=True)

    def __str__(self):
        return 'Review #{}'.format(self.id)


class WarrantyClaim(models.Model):
    cartitem = models.ForeignKey(CartItem)
    issue_details = models.TextField('Issue details')
    claim_time = models.DateTimeField('Claim date & time', auto_now_add=True)
    warranty_status = models.CharField('Status', max_length=10, default='claimed',
                                       choices=(('claimed', 'Claimed'),
                                                ('accepted', 'Accepted'),
                                                ('rejected', 'Rejected'),
                                                ('resolved', 'Resolved')))

    def __str__(self):
        return 'Warranty #{}'.format(self.id)


class StockTransfer(models.Model):
    from_stock = models.ForeignKey(Stock, related_name='from_stock', blank=True, null=True)
    to_stock = models.ForeignKey(Stock, related_name='to_stock')
    quantity = models.IntegerField('Quantity', default=1)
    transferred_at = models.DateTimeField('Transferred_at', auto_now_add=True)

    def __str__(self):
        return 'Transfer #{}'.format(self.id)


# import for registering signals
import main.signals

main/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=30, required=True)
    password = forms.CharField(max_length=50, required=True)
    phone_number = forms.CharField(max_length=30, required=False)
    home_address = forms.CharField(max_length=200, required=False)

    def clean_username(self):
        data = self.cleaned_data.get('username', None)
        if data is not None and User.objects.filter(username=data).count() > 0:
            raise forms.ValidationError("This username is already taken!")

    def clean_email(self):
        data = self.cleaned_data.get('email', None)
        if data is not None and User.objects.filter(email=data).count() > 0:
            raise forms.ValidationError("Account with this email already exists!")


class PhotoUploadForm(forms.Form):
    photo = forms.ImageField(required=True)

    def clean_photo(self):
         photo = self.cleaned_data.get('photo', False)
         if photo:
             if photo._size > 5 * 1024 * 1024:
                   raise forms.ValidationError("File too large. Upload a photo smaller than 5MB.")
             return photo


class ProfileEditForm(forms.Form):
    phone = forms.CharField(max_length=30, required=True)
    address = forms.CharField(max_length=200, required=False)

dashboard/views/mainview.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from dashboard.utils import *
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Sum
from django.utils import timezone
from django.contrib import messages
from dashboard.utils import get_hottest_items
import json


@login_required
@user_passes_test(lambda u: u.is_staff)
def dashboard_home_view(request):
    start_datetime = timezone.now() - timedelta(days=7)
    end_datetime = timezone.now()
    hottest = get_hottest_items(start_datetime, end_datetime)
    weekly_sales = weekly_sale_counts()
    return render(request, 'dashboard/dashboard.html', {'hottest': json.dumps(hottest),
                                                        'weekly': json.dumps(weekly_sales),
                                                        'products': [p.as_dict() for p in Product.objects.all()]})


@login_required
@user_passes_test(lambda u: u.is_staff)
def period_sales_view(request):
    today = None in (request.GET.get('startDateTime'), request.GET.get('endDateTime'))

    start_datetime = request.GET.get('startDateTime', datetime.today().strftime('%Y-%m-%d 00:00:00'))
    end_datetime = request.GET.get('endDateTime', datetime.today().strftime('%Y-%m-%d 23:59:59'))

    sales_set = get_all_sales_in_range(start_datetime, end_datetime)
    pending_set = get_all_sales_in_range(start_datetime, end_datetime, is_complete=False)

    revenue_completed = sales_set.aggregate(total=Sum('amount_charged')).get('total') or 0
    revenue_pending = reduce(lambda x, y: x + y.actual_price(), pending_set, 0)

    revenue = revenue_completed + revenue_pending

    return render(request, 'dashboard/reports/period_sales.html',
                  {'today': today,
                   'revenue': revenue,
                   'total_sales': sales_set.count(),
                   'orders_date': sales_set,
                   'start_datetime': start_datetime,
                   'end_datetime': end_datetime})


@login_required
@user_passes_test(lambda user: user.is_staff)
def item_sales_view(request):
    today = None in (request.GET.get('startDateTime'), request.GET.get('endDateTime'))

    start_datetime = request.GET.get('startDateTime', datetime.today().strftime('%Y-%m-%d 00:00:00'))
    end_datetime = request.GET.get('endDateTime', datetime.today().strftime('%Y-%m-%d 23:59:59'))

    start_datetime_obj = tz_aware_datetime_from_string(start_datetime)
    end_datetime_obj = tz_aware_datetime_from_string(end_datetime)

    top_items = get_hottest_items(start_datetime_obj, end_datetime_obj, 5)
    all_items = get_all_items_by_number_of_sales(start_datetime_obj, end_datetime_obj)
    print len(all_items)

    return render(request, 'dashboard/reports/item_sales.html',
                  {'today': today,
                   'top_items': json.dumps(top_items),
                   'all_items': all_items,
                   'total_items': len(all_items),
                   'start_datetime': start_datetime,
                   'end_datetime': end_datetime})


@login_required
@user_passes_test(lambda user: user.is_staff)
def report_to_xls(request):
    start_datetime = request.GET.get('startDateTime', datetime.today().strftime('%Y-%m-%d 00:00:00'))
    end_datetime = request.GET.get('endDateTime', datetime.today().strftime('%Y-%m-%d 23:59:59'))

    sales_set = get_all_sales_in_range(tz_aware_datetime_from_string(start_datetime),
                                       tz_aware_datetime_from_string(end_datetime))
    xls = generate_xls_1(sales_set)
    file_name = 'Sales_Report_({:%d-%m-%Y-%H-%M}).xls'.format(datetime.today())
    response = HttpResponse(content_type="application/ms-excel")
    response['Content-Disposition'] = 'attachment; filename={}'.format(file_name)
    xls.save(response)
    return response


@login_required
@user_passes_test(lambda user: user.is_staff)
def user_history_view(request):
    try:
        user = User.objects.get(username=request.GET.get('username'))
        purchases = user.customer.cart_set.all()
        return render(request, 'dashboard/reports/user_history.html', {'purchases': purchases,
                                                                       'target_user': user})
    except User.DoesNotExist:
        messages.error(request, 'User does not exist.')
        return HttpResponseRedirect('/dashboard')



@login_required
@user_passes_test(lambda user: user.is_staff)
def product_history_view(request):
    try:
        product = Product.objects.get(pk=int(request.GET.get('product_id')))
        history = []
        for ci in CartItem.objects.filter(product=product, cart__completed_at__isnull=False):
            history.append({'checkout_at': '{:%B %d, %Y}'.format(ci.cart.checkout_at),
                            'customer_name': ci.cart.customer.user.get_full_name(),
                            'username': ci.cart.customer.user.username,
                            'quantity': ci.quantity})
        return render(request, 'dashboard/reports/product_history.html', {'product': product,
                                                                          'history': history})
    except Product.DoesNotExist:
        messages.error(request, 'Product does not exist.')
        return HttpResponseRedirect('/dashboard')

main/templates/main/cart_dropdown.html
{% if user.is_authenticated and cart_items.count %}
    <div class="dropdown" id="cartDropdown" style="display: inline-block">
        <button class="btn btn-info navbar-btn navbar-right dropdown-toggle" data-toggle="dropdown">
            Cart
            &nbsp; <span class="badge badge-info">{{ cart_items.count }}</span> &nbsp;
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu" style="width: 450px; padding: 15px;">
            <div style="max-height: 450px; overflow-y: scroll; margin-bottom: 10px;">
                {% include 'main/cart_dropdown_contents.html' %}
            </div>
            <li>
                <div class="row">
                    <div class="col col-md-5">
                        <a href="{% url 'cart_clear' %}" class="btn btn-default btn-sm btn-block">
                            <span class="glyphicon glyphicon-trash"></span>
                            Clear cart
                        </a>
                    </div>
                    <div class="col col-md-7">
                        <a href="{% url 'cart_checkout' %}" class="btn btn-success btn-sm btn-block">
                            <span class="glyphicon glyphicon-ok"></span>
                            Proceed to Checkout
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
{% endif %}

main/templates/main/product_details.html
{% extends 'base.html' %}
{% load static %}
{% load markdown %}


{% block content %}
    <div class="row">
        <div class="col col-md-4" style=" text-align: center;">
            <div class="thumbnail">
                <img src="{{ product.get_photo_url }}" alt="product photo" style="max-width: 100%;">
                <div class="caption">
                    {% if product.photo_caption %}
                        <p>
                            <small>{{ product.photo_caption }}</small>
                        </p>
                    {% endif %}
                    <a href="{{ product.get_photo_url }}" class="btn btn-primary btn-xs" id="photoLightbox">
                        <span class="glyphicon glyphicon-zoom-in"></span>
                        Show full size
                    </a>
                    <script>
                        $('#photoLightbox').click(function (evt) {
                            evt.preventDefault();
                            $(this).ekkoLightbox();
                        });
                    </script>
                </div>
            </div>

        </div>
        <div class="col col-md-8">
            <h2>{{ product.name }}</h2>

            <table class="product-list-info-table">
                <tr>
                    <td><strong>Rating</strong></td>
                    <td><div class="rating" data-rating="{{ product.avg_rating }}"></div></td>
                </tr>
                <tr>
                    <td><strong>Price</strong></td>
                    <td><strong class="label label-primary">৳ {{ product.default_price | floatformat:'0' }}</strong></td>
                </tr>
                {% if product.warranty_period %}
                    <tr>
                        <td><strong>Warranty</strong></td>
                        <td>
                            {{ product.warranty_period }} months
                        </td>
                    </tr>
                {% endif %}
                {% if product.stock_quantity %}
                    <tr>
                        <td colspan="2">
                            <h4 class="text-success" style="margin: 0;">
                                <div class="glyphicon glyphicon-ok-circle"></div>
                                In sock
                            </h4>
                        </td>
                    </tr>
                {% endif %}
            </table>
            {{ product.description | markdown | safe }}
            <hr>

            {% if product.stock_quantity > 0 %}
                <form action="{% url 'product_add_to_cart' product.id %}" method="POST">
                    {% if product.productvariation_set.count or product.productattachment_set.count %}
                        <div class="row">
                            {% if product.productvariation_set.count %}
                                <div class="col col-md-6">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h5>Select variation</h5>
                                        </div>
                                        <table class="table table-hover variation-list">
                                            {% for variation in product.productvariation_set.all %}
                                                <tr>
                                                    <td>
                                                        <input type="radio" name="variation" value="{{ variation.id }}" id="vr_{{ variation.id }}" data-customprice="{{ variation.custom_price }}">
                                                    </td>
                                                    <td>
                                                        <label for="vr_{{ variation.id }}">
                                                            {{ variation.name }}
                                                        </label>
                                                    </td>
                                                    <td>
                                                        ৳ {{ variation.custom_price | default:product.default_price }}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                </div>
                            {% endif %}
                            {% if product.productattachment_set.count %}
                                <div class="col col-md-6">
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h5>Select attachments</h5>
                                        </div>
                                        <table class="table table-hover attachment-list">
                                            {% for attachment in product.productattachment_set.all %}
                                                <tr>
                                                    <td>
                                                        <input type="checkbox" name="attachment_{{ attachment.id }}" id="at_{{ attachment.id }}" data-extraprice="{{ attachment.extra_price }}">
                                                    </td>
                                                    <td>
                                                        <label for="at_{{ attachment.id }}">
                                                            {{ attachment.name }}
                                                        </label>
                                                    </td>
                                                    <td>
                                                        + ৳ {{ attachment.extra_price | default:0.0 }}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <hr>

                    {% endif %}

                    <div class="row">
                        <div class="col col-md-2">
                            <label for="itemQuantity">Select Quantity</label>
                        </div>
                        <div class="col col-md-2">
                            <input type="number" class="form-control" min="1" max="{{ product.stock_quantity }}" name="quantity" value="1" id="itemQuantity" required>
                        </div>

                        <div class="col col-md-4">
                            <h4>
                                Subtotal:
                                <span class="text-success">
                                    ৳ <span id="subtotal" data-defaultprice="{{ product.default_price }}">{{ product.default_price }}</span>
                                </span>
                            </h4>
                        </div>

                        <div class="col col-md-4">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success btn-block">
                                <span class="glyphicon glyphicon-shopping-cart"></span>
                                Add to cart
                            </button>
                        </div>

                    </div>
                    {% if product.offered_schemes.count %}
                        <div class="row">
                            <div class="col-md-12 installment-controls" style="margin: 20px 0 0;">
                                <p>
                                    <a href="javascript:$('.installment-controls p').toggle()">Show installment options</a>
                                </p>
                                <p style="display: none;">
                                    <label>Choose an installment option</label>
                                    &nbsp;&nbsp;&nbsp;
                                    <select name="chosen_scheme">
                                        <option value="0" selected>None</option>
                                        {% for scheme in product.offered_schemes.all %}
                                            <option value="{{ scheme.id }}">{{ scheme.name }}</option>
                                        {% endfor %}
                                    </select>
                                </p>
                            </div>
                        </div>
                    {% endif %}
                </form>
            {% else %}
                <div class="alert alert-danger">
                    <strong>Sorry!</strong>
                    This product is out of stock. Please try later.
                </div>
            {% endif %}



            <hr>

            {% if user.is_authenticated %}
            <button class="btn btn-success btn-sm pull-right" data-toggle="modal" data-target="#newReviewModal">
                <span class="glyphicon glyphicon-pencil"></span>
                Write a review
            </button>
            {% endif %}
            {% if product.review_set.count %}
                <h3 id="reviews">Reviews ({{ product.review_set.count }})</h3>
            {% else %}
                <h3 id="reviews">No reviews</h3>
            {% endif %}
            <br>
            {% for review in product.review_set.all %}
                <div class="row">
                    <div class="col col-md-2">
                        <img src="{{ review.customer.get_photo_url }}" class="review-user-img" alt="photo">
                    </div>
                    <div class="col col-md-10">
                        <strong>{{ review.customer.user.get_full_name }}</strong>
                        <div class="rating" data-rating="{{ review.rating }}"></div>
                        <p>
                            {{ review.message }}
                        </p>
                        {% if user.is_staff or user.id == review.customer.user.id %}
                            <a href="{% url 'remove_review' review.id %}" class="btn btn-danger btn-xs">Delete</a>
                        {% endif %}
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>


    <div class="modal fade" id="newReviewModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="{% url 'product_add_review' product.id %}" method="POST">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Write a review</h4>
                    </div>
                    <div class="modal-body">
                        {% csrf_token %}
                        <div class="form-group">
                            <strong>Select a rating:</strong>
                            &nbsp;&nbsp;
                            {% for r in '12345' %}
                                <label for="rv_{{ r }}">
                                    <input type="radio" id="rv_{{ r }}" name="rating" value="{{ r }}" required>
                                    {{ r }}
                                    &nbsp;&nbsp;
                                </label>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="message" placeholder="Message" required></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Submit review</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



{% endblock %}


{% block extra_scripts %}
    <script src="{% static 'vendor/lightbox/ekko-lightbox.min.js' %}"></script>
    <script>
    $(function () {
        $('.rating').each(function (_, el) {
            makeRatingStars($(el));
        });

        $('.attachment-list input, .variation-list input, input[name=quantity]').change(function () {
            $('#subtotal').text(calcualteTotal());
        });
    });
    </script>
{% endblock %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'vendor/lightbox/ekko-lightbox.min.css' %}">
    <style>
        .installment-controls p {
            margin: 0;
            padding: 0;
        }
    </style>
{% endblock %}